language: c

arch:
  - amd64
  - arm64 
#  - ppc64le
  - s390x 

compiler: 
  - gcc
  - clang

branches:
  only:
    - master

script:
  - make
  - ./turborc -e0 turborc
  - ./turborc -e40,41,42,43,44,45,48,49 turborc -t
  - ./turborc -e40,41,42,43,44,45,48,49 turborc 

matrix:
  include:
    - name: linux-ppc64le-gcc-9
      env: CC=gcc-9
      arch: ppc64le
      before_install:
        - sudo add-apt-repository -y ppa:ubuntu-toolchain-r/test
        - sudo apt-get -y update
        - sudo apt-get -y install gcc-9

    - name: windows-mingw-w64
      os: windows
      arch: amd64 
      script: 
        - mingw32-make
        - ./turborc -e0 turborc.exe

    - name: apple-macOS-xcode
      os: osx

